apiVersion: apps/v1
kind: Deployment
metadata:
  name: cshimegi-blog-api
  labels:
    app: blog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-api-deploy
  template:
    metadata:
      labels:
        app: blog-api-deploy
    spec:
      initContainers:
        - name: wait-for-init-db
          image: busybox
          command:
            - sh
            - -c
            - "until nc -zv blog-db-service 3306; do sleep 5; done"
      containers:
      - name: blog-post-deploy
        image: cshimegi/blog-mono:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: blog-config
