apiVersion: apps/v1
kind: Deployment
metadata:
  name: cshimegi-blog-db
  labels:
    app: blog-db
spec:
  selector:
    matchLabels:
      app: blog-db-deploy
  template:
    metadata:
      labels:
        app: blog-db-deploy
    spec:
      containers:
        - image: mysql:8.3.0
          name: blog-db-deploy
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: DB_ROOT_PASS
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: DB_PASS
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: DB_USER
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: DB_NAME
            - name: LANG
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: DB_LANG
          ports:
            - containerPort: 3306
              name: http-mysql
