apiVersion: v1
kind: Service
metadata:
  name: restaurant-api-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: restaurant-api-deploy
