apiVersion: v1
kind: Service
metadata:
  name: blog-db-service
spec:
  type: ClusterIP
  ports:
  - name: http-mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: blog-db-deploy
