services:
  restaurant-api:
    image: cshimegi/restaurant-api:latest
    ports:
      - "8080:8080"
    environment:
      DB_PASS: secret
      DB_USER: cshimegi
      DB_NAME: restaurant
      DB_HOST: restaurant-db-service
      DB_PORT: 3306
    depends_on:
      restaurant-db:
        condition: service_healthy
  restaurant-db:
    image: mysql:8.3.0
    hostname: restaurant-db-service
    environment:
      MYSQL_ROOT_PASSWORD: ahfwLEenAasASddkf==
      MYSQL_PASSWORD: secret
      MYSQL_USER: cshimegi
      MYSQL_DATABASE: restaurant
      LANG: C.UTF-8
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 10s
